LOCAL_PATH := $(call my-dir)/src
include $(CLEAR_VARS)
LOCAL_MODULE := noteye
LOCAL_SRC_FILES := $(LOCAL_PATH)/libnoteye.cpp
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)
LOCAL_SHARED_LIBRARIES := SDL2 SDL2_image SDL2_mixer SDL2_net SDL2_ttf lua
LOCAL_CFLAGS := -DOPENGL -DINTERNALONLY -DAVOID_FFI -DNOCONSOUT
LOCAL_LDLIBS := -lGLESv1_CM -lz
include $(BUILD_SHARED_LIBRARY)
